### ISSUE TITLE
Support for Permissions configuration when defining actions

### ISSUE THREAD

**Issue by gergumboc** [port-labs/terraform-provider-port-labs#55]
Hi,

Is it possible to specify RBAC permissions to port actions? I don't see any rbac-related configurations in the Port terraform provider docs. 
Basically, able to configure whatever is in the Permissions tab in Port actions via terraform.
![image](https://github.com/port-labs/terraform-provider-port-labs/assets/92191972/b9886552-2bc3-4049-bdf2-d32c36c6495e)

**Comment by dvirsegev** [comment]
Hi @gergumboc , Thank you for your suggestion! Can you please  add the request here? https://roadmap.getport.io
This is a blocker for you?

**Comment by PavelPikat** [comment]
@dvirsegev I've raised https://roadmap.getport.io/integrations/p/manage-permissions-via-terraform

It's not a blocker - we ended up using [restapi provider](https://registry.terraform.io/providers/Mastercard/restapi/latest/docs/resources/object), but because of how Port's API is structured around permissions (e.g. no ID for permission entity), it causes a diff for each plan/apply, and Terraform is sending PATCH requests to Port's API even if the permissions haven't changed

**Comment by Tankilevitch** [comment]
Released in https://github.com/port-labs/terraform-provider-port-labs/releases/tag/v1.7.1
